default: &default
  env: &env
    REPO: icebergdefender/clamav-alpine
    WANT_CLAMAV_VERSION: '0.100.0'

steps:
  - label: ':hammer: Build Dockerfile'
    commands:
      - echo "UH OH"
    <<: *default
